version: '3.1'

services:

  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 4000:4000

  frontend:
    build: ./frontend
    ports:
      - 8080:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
